# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ata_piix" "usbhid" "ums_realtek" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/652b4c57-3fb4-4025-a5e5-5d8c37b42e61";
      fsType = "ext4";
    };

  fileSystems."/share" =
    { device = "/dev/disk/by-uuid/6dd1854a-047e-4f08-9ca1-ca05c25d03af";
      fsType = "btrfs";
    };

  fileSystems."/mnt/hdd" =
    { device = "/dev/disk/by-uuid/fa3cda61-29bf-4727-946e-4b8bffd0acf3";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2329-0933";
      fsType = "vfat";
      options = [ "fmask=0770" "dmask=0770" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/58e17281-949a-4c23-8c1a-342b12e01ca2";
      fsType = "ext4";
    };

  fileSystems."/root/.cache/doc" =
    { device = "portal";
      fsType = "fuse.portal";
    };

  fileSystems."/root/.gvfs" =
    { device = "gvfsd-fuse";
      fsType = "fuse.gvfsd-fuse";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b0acebed-db7e-4127-a640-4e89db948912"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
